<div>
    <a href="/admin/cars">🔙 Retour</a>
</div>

<h1>Ajouter une nouvelle voiture</h1>
<form action="/admin/cars" method="post" novalidate>

    <div>
        <label for="input-label">Label :</label>
        <input type="text" name="label" id="input-label">
    </div>

    <div>
        <label for="input-seats">Place assises :</label>
        <input type="number" name="seats" id="input-seats">
    </div>

    <div>
        <label for="select-label">Motorisation :</label>
        <select name="energy" id="select-label">
            <option value="" disabled>Choisissez...</option>
            <!-- TODO: La boucle qui remonte les vraies motorisations -->
            <option value="1">Essence</option>
        </select>
    </div>

    <div>
        <label for="input-plate_number">Numéro d'immatriculation :</label>
        <input type="text" name="plate_number" id="input-plate_number">
    </div>

    <div>
        <label for="input-price_day">Prix par jour :</label>
        <input type="number" name="price_day" id="input-price_day">
    </div>

    <div>
        <label for="input-price_distance">Prix du kilomètre supplémentaire :</label>
        <input type="number" name="price_distance" id="input-price_distance">
    </div>

    <div>
        <label for="input-image">Image :</label>
        <!-- TODO: Gérer l'upload d'image avec input de type "file" -->
        <input type="text" name="image" id="input-image">
    </div>

    <div>
        <input type="submit" value="Ajouter">
    </div>

</form>