<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Une erreur est survenue - <Autocasse class="com"></Autocasse></title>
</head>
<body>
    <h1>Erreur serveur - 500</h1>
    <p>
        Quelque chose a disfonctionné et le serveur a pris feu. <br>
        Désolé vous ne puvez pas encore louer cette magnifiqaue Traban de 1950.
    </p>
</body>
</html>