<div>
    <a href="/admin/categories">🔙 Retour</a>
</div>

<h1><?php  printf('%s %s', $user->getFirstname(), $user->getLastname() ) ?></h1>
<ul>
    <li>Id: <?php echo $user->getId() ?></li>
    <li>Email: <?php echo $user->getEmail() ?></li>
    <li>Prénom: <?php echo $user->getFirstname() ?></li>
    <li>Nom: <?php echo $user->getLastname() ?></li>
    <li>Téléphone: <?php echo $user->getPhoneNumber() ?></li>
</ul>
